sudo: false
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g npm@next
- npm install -g grunt-cli
install: npm install
before_deploy:
- scripts/grunt_build.bash
- grunt zip
- grunt codedeploy
deploy:
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: Jj7g/2W66/6jUckPHpPdAxv+jhW4JCJACoNsvBufR8gtbfpYVGyYmdFa3zsOIUs0D4UZMH4uK/BhO19J+2r6FVBafWwfNLSbFtGzlx1nMOp3M3lqSbeqLdgeIQf9nFwqd4nFUpDOLMcsK7DqpQpyqAoCbSotxCcPFTy9pQ3o410=
    skip_cleanup: true
    bucket: hmda-pilot
    local_dir: dist
    upload-dir: develop
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: Jj7g/2W66/6jUckPHpPdAxv+jhW4JCJACoNsvBufR8gtbfpYVGyYmdFa3zsOIUs0D4UZMH4uK/BhO19J+2r6FVBafWwfNLSbFtGzlx1nMOp3M3lqSbeqLdgeIQf9nFwqd4nFUpDOLMcsK7DqpQpyqAoCbSotxCcPFTy9pQ3o410=
    bucket: hmda-pilot
    key: develop/hmda-pilot-codedeploy.zip
    application: hmda-pilot
    deployment_group: hmda-pilot-dev
    on:
      all_branches: true
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: Jj7g/2W66/6jUckPHpPdAxv+jhW4JCJACoNsvBufR8gtbfpYVGyYmdFa3zsOIUs0D4UZMH4uK/BhO19J+2r6FVBafWwfNLSbFtGzlx1nMOp3M3lqSbeqLdgeIQf9nFwqd4nFUpDOLMcsK7DqpQpyqAoCbSotxCcPFTy9pQ3o410=
    skip_cleanup: true
    bucket: hmda-pilot
    local_dir: dist
    upload-dir: master
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: Jj7g/2W66/6jUckPHpPdAxv+jhW4JCJACoNsvBufR8gtbfpYVGyYmdFa3zsOIUs0D4UZMH4uK/BhO19J+2r6FVBafWwfNLSbFtGzlx1nMOp3M3lqSbeqLdgeIQf9nFwqd4nFUpDOLMcsK7DqpQpyqAoCbSotxCcPFTy9pQ3o410=
    bucket: hmda-pilot
    key: master/hmda-pilot-codedeploy.zip
    application: hmda-pilot
    deployment_group: hmda-pilot-prod
    on:
      branch: master
